name: dex_text
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  webview_flutter: ^3.0.0
  dio: ^4.0.4
  syncfusion_flutter_charts: ^19.4.50
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/